### ISSUE TITLE
Compiling Error on macOS

### ISSUE THREAD

**Issue by 1900forever** [DCurrent/openbor#106]
Using the latest code to compile on macOS 10.13.6 with Xcode 10.1.
I was using the following command:

`
cd engine  
`
`
./darwin.sh
`

and the error was shown:
`
find: /lib: No such file or directory
`

How can I fix it? Thanks.

**Comment by DCurrent** [comment]
That's a Mac library. Sorry, but we dropped support for that some time ago. OpenBOR runs great on Wine.

**Comment by DCurrent** [comment]
After editing going through the toolchains and my own notes, I had edited my comment about 50 times, best I put everything in a new comment. Here's the deal:

The MacOS port is technically still supported, but it isn't supposed to be. I meant to drop it almost two years ago and evidently just forget to pull the trigger. So right now the toolchains are there and you can _attempt_ to compile. But they haven't been updated for years before that, and I had absolutely nothing to do with the port. It was grandfathered in and the guy who did it is long gone. I'd say your chances of getting it to work are pretty low, and there isn't much I can do to help.

All of the MAC guys in our community run OpenBOR on Wine and report it works perfectly, so that's your best bet. The next release will officially drop MacOS. I know that's probably not what you wanted to hear, but this just isn't a Mac project. I do appreciate the heads up.
