### ISSUE TITLE
logo.gif issues

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#127]
This is a old issue that has been around since I started with Openbor but thought I would raise it here.

logo.gif does not work properly. It only shows one of the images. If you have a logo with 2 separate images it never shows both.

Here is a current example. Has details about Thatcher Productions and second image is made on Openbor engine.

![logo](https://user-images.githubusercontent.com/45753033/54488824-0d10c880-48f2-11e9-9f64-c4ff35bdf589.gif)

**Comment by dbaldan** [comment]
I don't think its an issue. Just use multiple images on your logo.txt

**Comment by DCurrent** [comment]
Logo was never meant to support animation, and it's better not to so we can support true color. That's specifically what data/scenes/logo.txt is for, and its been around since the original BOR. Closing this as a non-issue.

**Comment by nsw27** [comment]
I think this may be prematurely closed. Logo.gif doesn't even play on android versions.

plus when removing logo.gif and instead using logo.txt the game engine crashes and says

Error loading background (PIXEL_x8/PIXEL_32) file 'data/bgs/logo'


in my scenes folder I have logo.txt 


[logo.txt](https://github.com/DCurrent/openbor/files/2975693/logo.txt)

**Comment by dbaldan** [comment]
There are two things here:
1- Nobody said to remove the logo.gif - we said to use logo.txt to create animations.
2- There is an issue here for sure -  logo.gif isn't showing in android port at all.

I will open a new report for this.

**Comment by DCurrent** [comment]
As mentioned above the logic behind logo.gif is doing exactly what is was meant to do since 2004, including telling you when the file is missing. Kludging up animated .gif support for logo just isn't logical, but I can look at allowing omission of the logo.gif file.

As for the Android, yes that is a completely separate issue and doesn't belong here. I would ask for a report, but looks like @dbaldan already wrote one.
