### ISSUE TITLE
Fails to build on aarch64 with Clang

### ISSUE THREAD

**Issue by jbeich** [DCurrent/openbor#138]
## Description
Regressed by 4d471b75707d. GCC is not affected. See [downstream logs](http://thunderx1.nyi.freebsd.org/data/latest-per-pkg/openbor/) for good/bad builds.

### Reproduce
```
$ make BUILD_LINUX=1 CC=cc
[...]
ld.lld: error: constants.c:(function mapstrings_transconst: .text+0x418C): improper alignment for relocation R_AARCH64_LDST64_ABS_LO12_NC: 0x35050C is not aligned to 8 bytes
ld.lld: error: constants.c:(function mapstrings_transconst: .text+0x41C4): improper alignment for relocation R_AARCH64_LDST64_ABS_LO12_NC: 0x350564 is not aligned to 8 bytes
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```
or
```
$ LDFLAGS=-fuse-ld=bfd make BUILD_LINUX=1 CC=cc
[...]
source/openborscript/constants.o: in function `mapstrings_transconst':
constants.c:(.text+0x418c): relocation truncated to fit: R_AARCH64_LDST64_ABS_LO12_NC against symbol `blkpains' defined in .data section in openbor.o
ld.bfd: constants.c:(.text+0x418c): warning: one possible cause of this error is that the symbol is being referenced in the indicated code as if it had a larger alignment than was declared where it was defined
constants.c:(.text+0x41c4): relocation truncated to fit: R_AARCH64_LDST64_ABS_LO12_NC against symbol `backblkpains' defined in .data section in openbor.o
ld.bfd: constants.c:(.text+0x41c4): warning: one possible cause of this error is that the symbol is being referenced in the indicated code as if it had a larger alignment than was declared where it was defined
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```
### Expected behavior
Builds fine as if 4d471b75707d was reverted.

### Environment
```
$ cc --version
FreeBSD clang version 8.0.0 (tags/RELEASE_800/final 356365) (based on LLVM 8.0.0)
Target: aarch64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

$ cc -Wl,--version
LLD 8.0.0 (FreeBSD 356365-1300003) (compatible with GNU linkers)

$ cc -fuse-ld=bfd -Wl,--version
GNU ld (GNU Binutils) 2.32

# gcc8 --version
gcc8 (FreeBSD Ports Collection) 8.3.0
```

### Version
- Unix aarch64
- 6311 or later

**Comment by DCurrent** [comment]
Could you double check the build? I don't compile on Linux, but I do know the only changes made in 4d471b7 were the addition of two constants, and nothing else. It's all but impossible for that to have any affect on compiling. Stranger things have happened, but it would greatly help to know for certain. Thanks! 

I'll also tag @Plombo as he will likely have greater insight on Linux issues than me.

**Comment by DCurrent** [comment]
TBH, I really don't care about Clang. You're kind of off the reservation there. We'll still try and help though.

First thing, could you double check the build? I don't compile on Linux, but I do know the only changes made in 4d471b7 were the addition of two constants, and nothing else. It's all but impossible for that to have any affect on compiling. It's more likely due to compounded changes from earlier builds. Stranger things have happened, but it would greatly help to know for certain. Thanks!

I'll also tag @Plombo as he will likely have greater insight on Linux issues than me.

**Comment by jbeich** [comment]
> First thing, could you double check the build?

See 66657298's [build log](https://github.com/DCurrent/openbor/files/3137852/openbor-6989.log) after reverting 4d471b75707d.

**Comment by Plombo** [comment]
Those errors are something really specific to aarch64. I won't be able to reproduce since I don't have an aarch64 build environment, but the one idea I have is maybe it doesn't like how the extern declarations in that commit are declared as "extern int*" but the actual definitions are of type "e_animations*". @jbeich, can you try changing the "extern int *" declarations made in that commit to "extern e_animations *" and see if that fixes it?

**Comment by jbeich** [comment]
> but the actual definitions are of type "e_animations*".

Where?
https://github.com/DCurrent/openbor/blob/02375fbcd9c3848045dd7d11819542e83ae46cb1/engine/openbor.c#L443
https://github.com/DCurrent/openbor/blob/02375fbcd9c3848045dd7d11819542e83ae46cb1/engine/openbor.c#L453

> can you try changing `extern int *` declarations made in that commit to `extern e_animations *` 

Doesn't help. I've tried both: changing only declaration and changing declaration and definition.

**Comment by DCurrent** [comment]
Well I was sure wrong about adding constants not breaking anything. My bad. Thanks for the fix gents.
