### ISSUE TITLE
png issue

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#155]
I had someone compile current PC version of engine for me and tried multiple branch versions yet they all have seem crash and error when using png images

It was mentioned on a issue or somewhere before that png files or how they were read were getting tweaked and I asked if it would affect existing method of using png and was told it wouldn't.... 

********** An Error Occurred **********
*            Shutting Down            *

Assertion `!"invalid PNG filter"' failed in function 'png_decode_regular' at source/gamelib/loadimg.c:380.
This is an OpenBOR bug.  Please report this at www.chronocrash.com.

**Comment by haxpor** [comment]
I did some quick research for you. That part of code handle about filtering of png image.
Could you try to check whether you apply any filter, or process anything on your png image? Likely that the engine doesn't know that type of filter, thus shout out like that in the log.

You can try to post your image here, so I can try to check which filter method it is.

**Comment by DCurrent** [comment]
There is absolutely something wrong with your images. I test exclusively with .png and the latest source with no issues at all. Since you mentioned using Paint, the most likely culprit is interlace.

**Comment by nsw27** [comment]
![altidle1](https://user-images.githubusercontent.com/45753033/59147092-a572a100-8a3a-11e9-86b1-cf3fe229939a.png)
![r24](https://user-images.githubusercontent.com/45753033/59147099-b91e0780-8a3a-11e9-99de-78f3401d4af2.png)

here are two different sprites. I use photoshop and MS Paint but then always go back to photoshop to reapply the palette settings (as MS Paint removes it when editing on my current laptop which sux… )

**Comment by DCurrent** [comment]
I just tested again. 

1. Just to make sure I had the latest source, I pulled the latest main branch from github compiled. 
2. Ran three different modules. One is a mix of .png and .gif, the other two are .png only. No issues. 
3. Inserted one of your images as a select portrait. No issues, aside from the obvious palette mismatch.
4. Tested again, this time using your image as a palette base. Again, no issues. 

There is no problem with the engine loading and running .png images. The only possible issue I could find is that you have a transparent color in your palettes - but since they loaded anyway that didn't matter either.

![bor - 0000](https://user-images.githubusercontent.com/5900142/59147533-e3d07780-89ca-11e9-8907-13aa6a9b8be9.png)
![bor - 0001](https://user-images.githubusercontent.com/5900142/59147534-e4690e00-89ca-11e9-9c8a-93ccef421662.png)

I'll leave this open for a few days just in case anyone else wants to test and chime in.

**Comment by haxpor** [comment]
@nsw27 When since the last time you work with png image without crash?

I can do reasonable **guess** here. If you said, you recently compile from source, then this might be related as [this change](https://github.com/DCurrent/openbor/commit/040f982a939eb0fc8bc2e2f6a850bc73532ace6c) applied into the source as of March 22. It will crash if detect malformed data in png at certain height of image.

You might try to remove such line as seen in above link to narrow down the problem and see if it works for you. Anyway it doesn't mean to be a clean fix. Although if it works, I believe your png images might have problem but silently accepted by the engine before this crash.

**Comment by DCurrent** [comment]
@haxpor, my test above is with latest master branch source. It includes @Plombo's change.

**Comment by msmalik681** [comment]
"I had someone compile current PC version of engine for me"

Try to compile the build yourself nothing but windows in needed just download extract then run engine/build.bat

**Comment by haxpor** [comment]
@DCurrent Ok DC.

Then problem is about image itself as DC said.

**Comment by DCurrent** [comment]
@haxpor maybe, but I'm not 100% sure. I was able to use @nsw27's example images without a problem. All I know is the latest master works as intended for correctly rendered .png files - and even has some tolerance for mistakes (see above about the the examples images having transparent color in them). I'm starting to think the real problem is _"I had someone compile current PC version of engine for me"_. 

There is no telling what version was actually compiled and used. Could have been a working branch or any number of things.

**Comment by haxpor** [comment]
Ohh, what @msmalik681 and @DCurrent said make sense. I totally didn't pay attention much to that part. Alright~

**Comment by dbaldan** [comment]
@nsw27 Can I give you an advice? You are making your life harder than it should be by using two different programs to handle the images.

Photoshop can do about 99% of the things Paint can - with the exception of non-antialiasing drawing shapes. I strongly suggest that you use Photoshop for that, it will give you tons of tools that are presented in Paint, like layers.

If PS is too heavy to be run on your machine (or you don't get along with it very well), I can give you some other suggestions:

Free
**GIMP** - https://www.gimp.org/
**Krita** - https://krita.org/en/

Paid, but very cheap
**Aseprite** - https://www.aseprite.org/ (its a very nice tool and has RotSprite built-in)

Paid
**Pro Motion** - https://store.steampowered.com/app/671190/Pro_Motion_NG/
I have a license for this and its an AMAZING tool. It has some tools that aren't presented in any other tool on the market. For Pixel Art, it puts Photoshop to shame.

**Comment by nsw27** [comment]
this was one I was sent from input rework branch (as my goal is to see if all controller issues have been fixed)

https://www.mediafire.com/file/uaw4ihagtgmayno/OpenBOR%283%29.exe

here is error log, as soon as I attempt to enter a level it crashes. 

[OpenBorLog.txt](https://github.com/DCurrent/openbor/files/3268862/OpenBorLog.txt)

and I have tried to compile engine myself

clicked green button to download zip
![Capture](https://user-images.githubusercontent.com/45753033/59151570-c35ef680-8a78-11e9-9d1b-1e249d144521.PNG)

then in openbor-master\openbor-master\engine i clicked on build and got this error

![error](https://user-images.githubusercontent.com/45753033/59151584-f73a1c00-8a78-11e9-8913-7a8c29b0a7d5.PNG)

**Comment by nsw27** [comment]
and here is the working build of openbor that I use

http://www.mediafire.com/file/n5fsbh5g85s779o/OpenBOR.zip/file

**Comment by msmalik681** [comment]
The openbor.res file should have been made within the compile process was there any previous errors ?

**Comment by msmalik681** [comment]
thanks @nsw27 this was a issue with compiling when not downloaded though GitHub I have amended the source code and you should be able to compile after I commit a update. please note the build and hash will show as all zeros unless manually updated in the version.sh
![buildfix](https://user-images.githubusercontent.com/31506138/59152678-f9808400-8a40-11e9-9197-d5cb5002cc05.gif)

**Comment by msmalik681** [comment]
Both images work fine in animation frames or by using loadsprite/drawsprite but I have recreated this bug by setting the images as "titleb.png" I get the exact same error.  I believe this is a issue with loadscreen32 function maybe the sprite are not matching the video mode or something.

@nsw27 how or where are you using these sprites ?

**Comment by nsw27** [comment]
tested your build msmalik

FYI I got this virus alert when building, I pressed allow

![trojan](https://user-images.githubusercontent.com/45753033/59158792-3f058580-8b03-11e9-856c-af028e818d68.PNG)

I then tested the build but get a error 


********** An Error Occurred **********
*            Shutting Down            *

Assertion `!"invalid PNG filter"' failed in function 'png_decode_regular' at source/gamelib/loadimg.c:380.
This is an OpenBOR bug.  Please report this at www.chronocrash.com.

[OpenBorLog.txt](https://github.com/DCurrent/openbor/files/3269502/OpenBorLog.txt)

**Comment by msmalik681** [comment]
@nsw27 
I only fixed the issue with you being able to compile the source code without GitHub and there should not be anything wrong with 7-zip as I downloaded it directly from the homepage.

**Comment by nsw27** [comment]
ok so I compiled and tested the engine. 

images now load and can play game which is great.... there was a issue I saw with aligning of panels

![empty - 0001](https://user-images.githubusercontent.com/45753033/59485045-9024c900-8eb7-11e9-888b-f8635cb4eecb.png)

normally the black bar fills screen properly. here is the code

`name	filter

type	panel
speed 10
noquake 1 1
facing 1
setlayer 999
subject_to_screen 1

offscreenkill 9999

palette none

anim	idle
	loop	0
	delay	5
	offset	0 0
	bbox	0 0 0 0
frame	data/bgs/streets/filterc.png
frame	data/bgs/streets/filterb.png
	frame	data/bgs/streets/filter.png`

i have tested other games and same thing occurs.

I also noticed i changed screenshot button to space button and could take screenshots everywhere but within actual stages. (do i need to open a new issue for this ?)

**Comment by dbaldan** [comment]
@nsw27 we need to split the issues here, or it gets confusing for the devs to take care.

About the png:
- please, check the information. Your image is **indeed** interlaced
![Image of Yaktocat](https://i.imgur.com/ExABboC.png)
https://i.imgur.com/ExABboC.png

- Also, your image has a wrong palette - there are two spots with almost the same color (255 255 255 vs 254 254 254) and this can lead you to issues
![Image of Yaktocat](https://i.imgur.com/38GifOw.png)
https://i.imgur.com/38GifOw.png

- Do not use interlaced PNG. This is meant for web browsers only. 

> When a non-interlaced PNG downloads in a browser, it downloads the image in one pass - from start to finish. An interlaced PNG downloads as a whole image very quickly, but at low quality, on each successive pass it downloads more of the detail, until the complete image has downloaded

About the engine update you made a terrible mistake, from a developer point of view: **Never**, ever, update a core without extensive testing. Just for reference, my downloads still uses the build 4432 (and I will only change it when I feel everything is okay, while I test another builds down on the road.

So I suggest you to revert the engine update on your game - and this can give you more headache, because the configuration files can corrupt save games or lead to bugs. To bypass this, you would need to change the .pak name, so the engine will create a new configuration file.

**Comment by Plombo** [comment]
@nsw27 I fixed the interlaced decoding error and merged it to master. You'll need to file a new bug for the panel alignment thing, though.

**Comment by nsw27** [comment]
I didn't mean to use interlaced and unsure how I did set it to interlaced in photoshop. is there a way to remove interlacing ?

BTW the png crash seems to be fixed now.

I needed to gamble with the latest engine as ive had people reporting controller issues for years now.... I wanted to test the controller fixes to engine because if we don't test things then when they are eventually released they could still be causing issues (like this png issue for example)

I will create another post for other related issue
