### ISSUE TITLE
Build versions

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#17]
Guys, I saw the latest release, which is build: 
OpenBOR_v3.0_Build_**4544** (October 3)

But how this could be possible if the last version was **v4569**, released in April 21?

If I can be honest, @DCurrent , those versions are starting to get very confuse and this is hurting the engine and its user base. We don't know anymore which is the latest version...

**Comment by whitedragon0000** [comment]
check latest svn version (actually 4546): [https://github.com/DCurrent/openbor/commit/286cc0726378d850253bb1eb6b248a40b7e291cf#diff-ad1943a9fd6d3d7ee1e6af41a5b0d3e7](url)

**Comment by dbaldan** [comment]
@whitedragon0000 what counts for the users are the releases, not the SVN.
Why you have closed this, since the issue wasn't fixed?

**Comment by DCurrent** [comment]
I believe I've found the confusion. My release 4453 had the right tag but a typo in the file name (4553), and near as I can tell @whitedragon0000 used the file name instead of tags as a version guide in his subsequent releases. Very easy mistake to make on both sides, but boy did it cause a mess. I just finished fixing up all the version tags and file names. We should be good to go moving forward.
