### ISSUE TITLE
Basemap (slope) makes picking up weapons difficult in some situations

### ISSUE THREAD

**Issue by 2blackbar** [DCurrent/openbor#172]
When i use 500 pixels long slope from height 0 pixels to 90 pixels then i have big trouble to pickup weapon , its not impossible but i have to pinpoint location exactly pressing attack for 50 times or more to pickup weapon, if i use the same slope of 500 pixels and height 90 to 90 then i can pickup weapon immediately on first try. Its like if bbox of weapon item shrinked to one pixel when its on basemap/slope and you have to pinpoint it exactly to pickup weapon.
Probably misallignment with entity due to slope shape creates that, i can pick subtype touch items without issues its only weapons  subtype that are problematic.
Maybe coords checks are too strict when picking up weapons, i tried to give bbox of weapon item z width of 30 but it didnt solved the problem.

**Comment by DCurrent** [comment]
Hey @2blackbar, sorry to take so long getting back to you. I'm looking at the code, and there actually isn't a Y or Base axis test at all. The engine only cares about X and Z alignment to pick up things. 

Mind testing this again? Turn on Debug->Basic Properties and compare positions when you are trying to pick something up. That might give us a clue where the failure is.

**Comment by dbaldan** [comment]
I can confirm this - getting items over basemap doesn't works sometimes.

**Comment by DCurrent** [comment]
@dbaldan, I still need more details. Did you compare positions of the item vs. collector? My guess is there is a Z axis issue we need to track down. It simply isn't possible for it to be a vertical issue because there's no vertical check I can find. At all. You could be 10K pixels above the item and OpenBOR won't care so long as you're aligned on X & Z. Which is itself oversight I'll need to look into, but that's another day.

**Comment by dbaldan** [comment]
@DCurrent yeah I think so. I haven't compared it yet, but I will try it soon. I think its a Z issue maybe.
