### ISSUE TITLE
Wii 240p output

### ISSUE THREAD

**Issue by mnx-xx** [DCurrent/openbor#186]
OpenBOR for WII natively runs in 480i mode, can be changed to 240p? Or can be implement any kind of video mode changer? Playing 480i arcade games on WII with CRT monitor is not really what arcade games was for..

**Comment by DCurrent** [comment]
Unless the Wii version does something really wacky I don't know about (@Plombo please clarify here), OpenBOR video output is controlled by the game module, not the engine. Some authors will make their modules with the Wii in mind, some don't care about the Wii at all. It's up to them, not us.

**Comment by Plombo** [comment]
On the Wii, the output to the TV is 480i regardless of the game's source resolution. @mnx-xx here is asking for support for 240p, which the Wii apparently supports if it's connected to the right TV with component cables. It seems like a reasonable feature request to me.

Though I don't think I could implement or test it myself, since I don't have a Wii component cable, and my TV probably doesn't support 240p.

**Comment by DCurrent** [comment]
@Plombo ahh, gotcha. It's not something I can do at all. I don't have a Wii and am up to my armpits in engine logic again, but I'm not going to be a wet blanket if someone wants to step in and try.

**Comment by DCurrent** [comment]
Closing ticket. I'm sorry, but there's really no feasible way for me to fill this request. I do not own a Wii, and do not know anything about porting/coding for it.
