### ISSUE TITLE
Building on x64 Linux fail

### ISSUE THREAD

**Issue by Snipie** [DCurrent/openbor#19]
Hello,
I try to build using ./build 4 amd64 building starts but the compiler gives multiple warnings concerning sprintf.
I removed the -Werror flag from the Makefile it builds and runs but sometimes it gives me Segmentation Fault.

**Comment by n3f4s** [comment]
Hi,
The error is:
```
source/gamelib/packfile.c: In function 'casesearch':
source/gamelib/packfile.c:324:33: error: 'sprintf' may write a terminating nul past the end of the destination [-Werror=format-overflow=]
         sprintf(fullpath, "%s/%s", dir, entry->d_name);
                                 ^
source/gamelib/packfile.c:324:9: note: 'sprintf' output 2 or more bytes (assuming 257) into a destination of size 256
         sprintf(fullpath, "%s/%s", dir, entry->d_name);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:655: source/gamelib/packfile.o] Error 1
```

It's caused by the fact that the size of ``dir`` added to the size of ``entry->d_name`` is greater than 256 (the size of ``fullpath``).
Since the overflow is an undefined behaviour (and not an error), the compiler issue just a warning.
``-Werror`` cause transform the warning into errors. That's why the build is a success without it (even if there are warnings). The error is not fixed. The overflow is still there, hence the intermittent segfault.

**Comment by DCurrent** [comment]
I increased the size of fullpath to 1024 in 7f1664da942221f0a59e94a58533219c40fff066. See if that helps.
