### ISSUE TITLE
Git Clone 1.4 GB?

### ISSUE THREAD

**Issue by inukaze** [DCurrent/openbor#202]
Hi there, i just want to know if you know when you use

```
git clone https://github.com/DCurrent/openbor
Cloning into 'openbor'...
remote: Enumerating objects: 25389, done.
remote: Total 25389 (delta 0), reused 0 (delta 0), pack-reused 25389
Receiving objects: 100% (25389/25389), 1.21 GiB | 152.00 KiB/s, done.
Resolving deltas: 100% (16149/16149), done.
Checking out files: 100% (661/661), done.
```

Well i think this is too much size for OpenBor Engine but i found this file :
openbor/.git/objects/pack/pack-3d9aed063631b8bf68a30b642210e567884187fc.pack

![OpenBir_GitClone](https://user-images.githubusercontent.com/1647332/83522259-6ab91280-a4ae-11ea-8ec7-fdac706ae1c8.png)

This file is really need it for compile the engine from source?

Well under 

Slackware 14.2 (32 Bits)
Slackware64 14.2 (64 Bits)

Compile without problems :D

**Comment by danielt3** [comment]
OpenBor has a philosophy of shipping most of the tools needed to build it (at least to build in Windows hosts). This increased the repo a lot but makes it really easy to build when you are done. This is a tradeoff: setting up these tool can be *really* hard (specially in Windows environments) but providing them ready-to-use increases the repo size.

Personally, I'm really happy with the current choice because actual building executables means not much more than clonning, opening a shell and calling a build script (I just did exactly this and it worked flawlessly).

**Comment by DCurrent** [comment]
@danielt3 pretty much nailed it. OpenBOR is a Windows first application - everything else is a port. The toochain is huge, but really, REALLY simplifies the compile process. There are no doubt small pieces here and there we don't need, but trying to ferret them all out would take months and cause more problems than it solves.
