### ISSUE TITLE
Damageonland issue

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#22]
I discovered that when you set a DAMAGEONLAND (as a attackbox complement or by script), the target wont react (IOW, its velocity won't change) by any other attack (even if the knockdown power is bigger) until it lands.

This breaks combos where you need a first attack which throws the target high in the air and wants to hit it again, while having it to receive damage from the fall from the a great altitude.

OpenBoR v3.0 Build , Compile Date: Dec 22 2016 - OpenBOR_v3.0_Build_4419

**Comment by whitedragon0000** [comment]
Code seems ok.. Can you post a video example?

**Comment by dbaldan** [comment]
@whitedragon0000 do you have my Avengers game, right?]
Choose THOR, grab an enemy, input UP+ATTACK. He will throw the enemy upward.
Right after it, input DOWN, UP, ATTACK. He will execute an upper and the enemy will receive the damage, but no change in the hurt animation.

**Comment by whitedragon0000** [comment]
ok, fixed!!

**Comment by whitedragon0000** [comment]
Working on

**Comment by dbaldan** [comment]
Thanks

**Comment by whitedragon0000** [comment]
Well...
So, try to talk about the solution. 
This bug exists because when damage on landing is set, the enemy doesn't change animation. Why? Because there is a return 1 before the fall animation change in common_takedamage() function.
I'm thinking... 
I can add an entity prop to store latest attack_type example attack_normal or attack_normal9 etc...
Then I can delete that "return 1" and set the attack_type when the enemy lands....
What do you think about this?
In fact when damage on landing is set the attack_type is force set to atk_land.
Tell me what you think 😀


I can instance adding to entity a s_collision_attack as last_atk (more memory) for any change in the future or just an int last_atk_type to store just the last atk_type....
Tell me  ;)

**Comment by DCurrent** [comment]
We need to look deeper into this or find another solution. Using ATK_LAND is intended behavior. Do not change it.

**Comment by dbaldan** [comment]
I agree with DC. ATK_LAND is very useful. If to fix this issue (which is a minor issue) we will break other more useful stuff, so let it as is.

**Comment by whitedragon0000** [comment]
Ok perfect.

**Comment by whitedragon0000** [comment]
Dol issue is pretty fixed!

**Comment by dbaldan** [comment]
Indeed, thanks!
