### ISSUE TITLE
Games Crash on load.

### ISSUE THREAD

**Issue by DaviGamerXP** [DCurrent/openbor#230]
I'm using a OpenBOR 3.0 build, and downloaded seven PAK. files. But there's two of them which don't work, when i try playing these games in OpenBOR they show the loading screen, then OpenBOR just crashes, it disappears. Every other game i have downloaded works, but not these two for some reason, and apparently i'm the only one having this issue. I'm also sending the PAK files which don't work so we can find out if the issue is the pak files or openBOR on my computer, Justice League Legacy and He-Man.

### Expected behavior
I expect the games to load so i can play them.

### Version
OpenBOR 3.0.

- Platform
Windows 7 x64

Link to download the pak files:
https://f-cdn.gamejolt.net/data/games/8/207/547957/files/604f5b409f508/jllv120.rar?secure=04wsm7TVirtGlLuNGl2U9w%2C1622003832

https://f-cdn.gamejolt.net/data/games/0/184/19434/files/5f0e2e5a962c2/he-man-pc.zip?secure=IdHnwmm6coqDup0GIKIc1A%2C1622000651

**Comment by dbaldan** [comment]
@DaviGamerXP I am afraid this issue is more suited to be post on the forum, not here, because its not an OpenBOR bug.
If you try to run a game using an older build (or, in some cases, newer too) than the one the coder used to develop his game, it won't work.

For example, Justice League legacy needs build 6412. If I am not wrong, if you use a build lower than 6330, it won't run because Zvitor uses some new animations which were added in build 6330, like WIN.

Probably, is the same case of He-Man.

Feel free to report it on the forum http://www.chronocrash.com/forum/

**Comment by DaviGamerXP** [comment]
Where can i download Build 6412? I can't find it anywhere
