### ISSUE TITLE
Android touch bug

### ISSUE THREAD

**Issue by whitedragon0000** [DCurrent/openbor#37]
Unresolved touch (lag?) bug on android port with SDL2 update..
I ask any help...
After any tests I can't fix this issue...

**Comment by dbaldan** [comment]
Can't we revert the sdl update?

**Comment by whitedragon0000** [comment]
But in old sdl2 we have other bugs...
We need to know hot to fix it...

**Comment by dbaldan** [comment]
Seams to be related with SDL2 itself, not an OpenBOR bug.

Take a look at this, maybe this helps:
https://discourse.libsdl.org/t/touch-input-jitter-on-android/21760
https://forums.libsdl.org/viewtopic.php?p=50274

**Comment by whitedragon0000** [comment]
I see... Thanks for your help O'!
I will open a new thread in sdl2 forum..

**Comment by dbaldan** [comment]
@whitedragon0000 you mean that non-wide screen modules do work if they aren't stretched out?
I don't have any non-wide module on my phone and, as far as I know, I can't change the video settings.

Here are my settings https://imgur.com/pO0e5Gc

**Comment by whitedragon0000** [comment]
Change preserve aspect ratio

**Comment by dbaldan** [comment]
BINGO. It works!
Instead of "preserve aspect ratio", if you choose "stretch", the control lag is gone.

**Comment by whitedragon0000** [comment]
Yes! But now... We need to know... Why??
I think that we need to have a surface base under the main game surface to fill all screen. 
Now I can't compile...

**Comment by whitedragon0000** [comment]
Actually I have no idea how to fix the SDL bug...

**Comment by dbaldan** [comment]
Dunno.if this version is old, but the custom build his has made doesn't have this lag
http://www.chronocrash.com/forum/index.php?topic=2025.msg52623#msg52623

**Comment by msmalik681** [comment]
That stand alone version was based on build v4699 as there was so much talk about input lag on latest version.

I do not think the issue is input lag but a performance issue as I used a update script on my Tekken mod and it was not working right like system tics were being missed.  So if system tics are being missed it would also miss some inputs.  I will do some test to see how the new custom build works on the latest openbor build.

@WD can you confirm if we are running the latest [opengl es 3.1](https://www.khronos.org/news/press/khronos-releases-opengl-es-3.1-specification) on openbor ? If not could it be upgraded ?

have you incorporated "SDL_ANDROID_BLOCK_ON_PAUSE" as this would be needed for adverts to run over the app.

**Comment by whitedragon0000** [comment]
Here the SDL topic:
https://discourse.libsdl.org/t/android-touch-issue-after-update-sdl-from-2-0-1-to-2-0-8/24142/8
Maybe the issue is related to setlogicalsize scaling

**Comment by wd** [comment]
@msmalik681 You mentioned the wrong people, I don't know what you are talking about.

**Comment by msmalik681** [comment]
Sorry I had no idea there was a "wd" user I was using it as short for White Dragon.

@whitedragon0000 
Congratulations on fixing the bug but there is still a issue with touchscreen.  All touchscreen buttons do not work when remapping buttons.

When you have a wired keyboard connected all buttons work except return as the start button.  As ilu mentioned the gamepad support is more important but i thought i would mention this too.

**Comment by whitedragon0000** [comment]
Ok, so please open SDLActivity.java and see public boolean onKey() methods.
Try to change and test key mapping and compile. 
Help me about this because I have not Bluetooth devices.
Thanks

**Comment by whitedragon0000** [comment]
Big thanks!!
I can close this bug finally!!
